spring.application.name=backend_semi
server.port=9000

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# ${????:???} : ????? ??? ? ????? ???? ????? ??? ?? ?? ???
# ????? ???? ???? ?? ?? ??
# ??? ??: ??? C:\shop\images\, ??? ????? ??? (S3 ??? ???)
productImageLocation=${IMAGE_PATH:C:\\shop\\images\\}
uploadPath=${UPLOAD_PATH:file:///C:/shop/images/}

# DB: ??? ? MySQL, ??? RDS ??? ????? ??
spring.datasource.url=jdbc:mysql://localhost:3306/wls?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:mysql}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

allowPublicKeyRetrieval=true

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ???? ??? github? ????? ??? ???? ???
# ?? ????? ??? ???? ???? ??? ??? ???? ???? JwtUtil.java? ?? ??
jwt.private-key=${JWT_PRIVATE_KEY:}
jwt.public-key=${JWT_PUBLIC_KEY:}

# ???? ???? ?? ??? ??
jwt.private-key-path=backend_semi/secrets/jwt-private.pem
jwt.public-key-path=backend_semi/secrets/jwt-public.pem
jwt.expiration=3600000

server.servlet.session.timeout=120m

# ===== ?? ??? ?? =====
# ?? ?? ?? (???? ????? ???)
file.upload-dir=${FILE_UPLOAD_DIR:C:/upload/files}
# ???? ?? ?? ???
file.access-prefix=/files

# ???? ?? ?? (?? 1MB? ?? ??? ?? ??)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ===== AWS S3 ?? (?? ? ?? ????? ?? ??? ??) =====
# ?? ???? ???? S3 ??? ???
cloud.aws.s3.bucket=${S3_BUCKET:}
cloud.aws.region=${S3_REGION:ap-northeast-2}
cloud.aws.credentials.access-key=${S3_ACCESS_KEY:}
cloud.aws.credentials.secret-key=${S3_SECRET_KEY:}